import type { Metadata } from 'next'
import './globals.css'
import { RootLayout, RootLayoutProps } from '@/layouts/root'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout(props: RootLayoutProps) {
  return <RootLayout {...props} />
}
